Feature/eodhp 813 detailed http response codes for stac fast api
EO-DataHub/stac-fastapi-elasticsearch-opensearch pull request #25
Opened 2024-09-24 14:47 UTC by shahidraza-telespazio

Updated Error Codes for Collection, Catalog, and Items Access

The applied changes ensure the correct error codes (401 and 403) are returned in the following scenarios:

Unauthenticated Access: Users who are not logged in cannot access any private workspaces, whether their own or others’.
Authenticated Access: Logged-in users can only access their own private workspaces.
Public Access: Access to public workspaces remains unaffected, regardless of the user’s login status.

2024-09-25 09:52 UTC, tjellicoe-tpzuk requested changes
Looks good, I would also suggest the following updates too:
- add the same 401 and 403 functionality to:
  - `all_catalogs` if a catalog_path is provided - will require you to use the `find_catalog` function as on line 466
  - `post_search` where it currently returns a `403` response

Unrelated to this PR but could you also fix the bug on line 443 where it should return a `Catalog` rather than a `Collection`

You can also add a few lines to the changelog to state what has been updated.

2024-09-25 09:52 UTC, tjellicoe-tpzuk commented on stac_fastapi/core/stac_fastapi/core/core.py
> +                    status_code=403, detail="User does not have access to this collection"
I realise I suggested this update, but now see it should read `User does not have access to this catalog`

2024-09-30 10:29 UTC, tjellicoe-tpzuk commented on stac_fastapi/core/stac_fastapi/core/core.py
> +                    status_code=403, detail="User does not have access to this collection"
Has this been resolved?

2024-09-30 10:32 UTC, shahidraza-telespazio commented on stac_fastapi/core/stac_fastapi/core/core.py
> +                    status_code=403, detail="User does not have access to this collection"
Yes I have updated it back to ""User does not have access to this catalog"

2024-09-30 10:33 UTC, tjellicoe-tpzuk approved these changes
Looks good, nice work!
Please add a few lines to the changelog to clarify the changes, then all good!

2024-09-30 10:52 UTC, merged